export const OPEN_SIDE_TAB = 'OPEN_SIDE_TAB';
export const CLOSE_SIDE_TAB = 'CLOSE_SIDE_TAB';
export const OPEN_SETTING = 'OPEN_SETTING';
export const CLOSE_SETTING = 'CLOSE_SETTING';

/** header */
export const REQUEST_ACCOUNT_INFO = 'REQUEST_ACCOUNT_INFO';
export const COMPLETE_ACCOUNT_INFO = 'COMPLETE_ACCOUNT_INFO';

/** account */



/** itemList */
export const CHANGE_TO_LIST_VIEW = 'CHANGE_TO_LIST_VIEW';
export const CHANGE_TO_GRID_VIEW = 'CHANGE_TO_GRID_VIEW';
export const REQUEST_LOAD_ITEM_CONTENT_LIST = 'REQUEST_LOAD_ITEM_CONTENT_LIST';
export const COMPLETE_LOAD_ITEM_CONTENT_LIST = 'COMPLETE_LOAD_ITEM_CONTENT_LIST';


