export const INCREMENT = 'COUNTER_INCREMENT';
export const INCREMENT_SUCCESS = 'INCREMENT_SUCCESS';
export const DECREMENT = 'COUNTER_DECREMENT';

export const OPEN_SIDE_MENU = 'OPEN_SIDE_MENU';
export const OPEN_SETTING = 'OPEN_SETTING';

