export const OPEN_SIDE_TAB = 'OPEN_SIDE_TAB';
export const CLOSE_SIDE_TAB = 'CLOSE_SIDE_TAB';
export const OPEN_SETTING = 'OPEN_SETTING';
export const CLOSE_SETTING = 'CLOSE_SETTING';
export const OPEN_ITEM_DETAIL_MODAL = 'OPEN_ITEM_DETAIL_MODAL';
export const CLOSE_ITEM_DETAIL_MODAL = 'CLOSE_ITEM_DETAIL_MODAL';


/** header */
export const REQUEST_ACCOUNT_INFO = 'REQUEST_ACCOUNT_INFO';
export const COMPLETE_ACCOUNT_INFO = 'COMPLETE_ACCOUNT_INFO';

/** account */

/** addContent */
export const OPEN_ADD_CONTENT_MODAL = 'OPEN_ADD_CONTENT_MODAL';
export const CLOSE_ADD_CONTENT_MODAL = 'CLOSE_ADD_CONTENT_MODAL';
export const MOVE_CONTENT_ADD_MODAL = 'MOVE_CONTENT_ADD_MODAL';
export const SET_ADD_CONTENT = 'SET_ADD_CONTENT';
export const CHANGE_TAG_NAME_ADD_CONTENT_MODAL = 'CHANGE_TAG_NAME_ADD_CONTENT_MODAL';
export const REQUEST_CREATE_TAG_ADD_CONTENT_MODAL = 'REQUEST_CREATE_TAG_ADD_CONTENT_MODAL';
export const COMPLETE_CREATE_TAG_ADD_CONTENT_MODAL = 'COMPLETE_CREATE_TAG_ADD_CONTENT_MODAL';
export const FAIL_CREATE_TAG_ADD_CONTENT_MODAL = 'FAIL_CREATE_TAG_ADD_CONTENT_MODAL';
export const REQUEST_DELETE_TAG_ADD_CONTENT_MODAL = 'REQUEST_DELETE_TAG_ADD_CONTENT_MODAL';
export const COMPLETE_DELETE_TAG_ADD_CONTENT_MODAL = 'COMPLETE_DELETE_TAG_ADD_CONTENT_MODAL';
export const REQUEST_SAVE_ADD_CONTENT = 'REQUEST_SAVE_ADD_CONTENT';
export const SUCCESS_SAVE_ADD_CONTENT = 'SUCCESS_SAVE_ADD_CONTENT';
export const FAIL_SAVE_ADD_CONTENT = 'FAIL_SAVE_ADD_CONTENT';


/** itemList */
export const CHANGE_TO_LIST_VIEW = 'CHANGE_TO_LIST_VIEW';
export const CHANGE_TO_GRID_VIEW = 'CHANGE_TO_GRID_VIEW';
export const REQUEST_LOAD_ITEM_CONTENT_LIST = 'REQUEST_LOAD_ITEM_CONTENT_LIST';
export const COMPLETE_LOAD_ITEM_CONTENT_LIST = 'COMPLETE_LOAD_ITEM_CONTENT_LIST';
export const REQUEST_CHANGE_TO_DISPLAY_ITEM_LIST = 'REQUEST_CHANGE_TO_DISPLAY_ITEM_LIST';
export const COMPLETE_CHANGE_TO_DISPLAY_ITEM_LIST = 'COMPLETE_CHANGE_TO_DISPLAY_ITEM_LIST';
export const REQUEST_CLEAR_TO_DISPLAY_ITEM_LIST = 'REQUEST_CLEAR_TO_DISPLAY_ITEM_LIST';
export const COMPLETE_CLEAR_TO_DISPLAY_ITEM_LIST = 'COMPLETE_CLEAR_TO_DISPLAY_ITEM_LIST';
export const REQUEST_CLEAR_EDIT_TAG_ITEM_LIST = 'REQUEST_CLEAR_EDIT_TAG_ITEM_LIST';
export const COMPLETE_CLEAR_EDIT_TAG_ITEM_LIST = 'COMPLETE_CLEAR_EDIT_TAG_ITEM_LIST';

/** history */
export const MOVE_PAGE = 'MOVE_PAGE';

/** tagging image */
export const OPEN_EDIT_TAG_MODAL = 'OPEN_EDIT_TAG_MODAL';
export const CLOSE_EDIT_TAG_MODAL = 'CLOSE_EDIT_TAG_MODAL';
export const TAGGING_IMAGE_REQUEST = 'TAGGING_IMAGE_REQUEST';
export const TAGGING_IMAGE_SUCCESS = 'TAGGING_IMAGE_SUCCESS';
export const TAGGING_IMAGE_FAILED = 'TAGGING_IMAGE_FAILED';


